-- Enabled now even though nothing queries it yet: a later session adds a
-- recommendation feature that stores opinion embeddings in a vector column, and
-- having the extension present from the first migration keeps that change purely
-- additive. The base image (pgvector/pgvector) ships the extension.
CREATE EXTENSION IF NOT EXISTS vector;

-- Columns mirror the Book struct in internal/books/book.go. IDs are generated by
-- the application (hex, matching MemoryStore) rather than the database, so id is
-- TEXT rather than a serial/uuid default.
CREATE TABLE IF NOT EXISTS books (
    id         TEXT PRIMARY KEY,
    isbn       TEXT,
    title      TEXT NOT NULL,
    author     TEXT NOT NULL,
    status     TEXT NOT NULL,
    rating     INTEGER NOT NULL DEFAULT 0,
    opinion    TEXT,
    tags       TEXT[],
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
